### ISSUE TITLE
inconsistent coloring

### ISSUE THREAD

**Issue by jedahan** [ur0/lolcat#1]
ruby lolcat makes a nice rainbow of the entire buffer, instead of breaking line by line:

### ruby
<img width="814" alt="ruby lolcat" src="https://cloud.githubusercontent.com/assets/32407/22772188/44446162-ee69-11e6-88f8-af54d160011d.png">

### rust
<img width="815" alt="rust lolcat" src="https://cloud.githubusercontent.com/assets/32407/22772187/4443bdb6-ee69-11e6-9a54-50e10eaef35d.png">

**Comment by ur0** [comment]
The Ruby version resets the seed across lines. Totally forgot about that.
