### ISSUE TITLE
lolcat shouldn't change your bg color

### ISSUE THREAD

**Issue by ghost** [ur0/lolcat#10]
Currently lolcat changes your terminal background color to black. The original lolcat doesn't do this.

Black portion is your version of lolcat, bottom half is with original authors, in ruby.

![2020-03-18_00-00](https://user-images.githubusercontent.com/980/76924016-792e5f80-68ab-11ea-959d-3c687c853707.png)

**Comment by SlooowAndFurious** [comment]
It looks like commit [52e3ff7](https://github.com/ur0/lolcat/commit/52e3ff7b2d3edefa6af522af5a4cc07d9af1904b) fixed this issue. It should be closed now

**Comment by ghost** [comment]
I can confirm this is fixed. Thank you!
