### ISSUE TITLE
lolcat doesn't work on my Ubuntu 21.x

### ISSUE THREAD

**Issue by STashakkori** [ur0/lolcat#16]
Confirmed it works on ubuntu 20.x but the colors don't work properly for any lolcat distribution on 21.x. Have tried with many different lolcat versions. Text is gray and occasionally displays a character with a colored background or blinking

**Comment by magnus-ISU** [comment]
This is more likely due to your terminal emulator than lolcat itself. What is your terminal emulator?

**Comment by magnus-ISU** [comment]
I checked on the latest release of ubuntu with a fresh install and it does work. So most likely Ubuntu fixed their terminal.

Reopen if this is again a problem, but it shouldn't be.
