### ISSUE TITLE
rainbow effect gone

### ISSUE THREAD

**Issue by deathtrip** [ur0/lolcat#19]
I upgraded from commit 31 to commit 54, and the rainbow effect is gone in the new version.
Now every line starts with the same color, whereas previously it shifted the starting color a bit, making the output much more vibrant.
commit 31:
![old-lolcat](https://user-images.githubusercontent.com/8403455/153899964-9716a1f5-9f6c-4930-bfe1-da017217a80c.jpg)
commit 54:
![new-lolcat](https://user-images.githubusercontent.com/8403455/153900175-9850ff15-09c6-48e7-a0ac-ae36c2025b21.jpg)

**Comment by magnus-ISU** [comment]
Sorry, this was a 1-line screwup I introduced. Should be fixed now.
