### ISSUE TITLE
Update crate for lolcat

### ISSUE THREAD

**Issue by magnus-ISU** [ur0/lolcat#21]
How do we do that? @ur0 

Currently, it installs a previous version if I run `cargo install lolcat`. I assumed it tracked this repository directly, but I guess not.

**Comment by ur0** [comment]
Hey, thanks for all the help! For now, the package is released manually with cargo publish. I’ll add you there too once you create an account. It’d be great to be able to use GH actions to auto release on tags.

**Comment by magnus-ISU** [comment]
I created an account

**Comment by ur0** [comment]
…and invited. Cheers!

**Comment by magnus-ISU** [comment]
How do I accept the invite? `cargo publish` didn't work
```
  the remote server responded with an error: this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

**Comment by magnus-ISU** [comment]
sorry got it
