### ISSUE TITLE
lolcat --help should display its help as a rainbow, if supported

### ISSUE THREAD

**Issue by jedahan** [ur0/lolcat#3]
:D

**Comment by ur0** [comment]
I'm not really sure that `clap` allows this. Trawling through all the documentation I can.

**Comment by Hackinet** [comment]
Such Evil. Much Wow.

**Comment by magnus-ISU** [comment]
I'm not sure if the developer still will update this, but I wrote my own solution as the merge request didn't seem to work for me.

https://github.com/magnus-ISU/lolcat-lolhelp

It's pretty bad, I need to get rid of some code duplication.

**Comment by magnus-ISU** [comment]
Took another look at this and the code duplication is fixed, so its a good option now.

**Comment by ur0** [comment]
Fixed in #17, thanks @magnus-ISU!
