### ISSUE TITLE
snap package for lolcat

### ISSUE THREAD

**Issue by simos** [ur0/lolcat#4]
I wrote an article about lolcats and how to create snap packages for them,
https://blog.simos.info/how-to-make-a-snap-package-for-lolcat-with-snapcraft-on-ubuntu/
I included this version of lolcat as well!

**Comment by ur0** [comment]
That's great. I'll fix on the existing character code issue ASAP and add the snap-install method to the readme too.

Great blog post and thanks for featuring this project.

**Comment by ur0** [comment]
An year too late, but [there](https://snapcraft.io/lolcat-rs) you go.
